const crimes = [
    {
      crime: 'Murder',
      location: 'New York City',
      year: 2023,
      cases: 390,
    },
    {
      crime: 'Murder',
      location: 'New York City',
      year: 2024,
      cases: 375,
    },
    {
      crime: 'Rape',
      location: 'New York City',
      year: 2023,
      cases: 1462,
    },
    {
      crime: 'Robbery',
      location: 'New York City',
      year: 2023,
      cases: 16822,
    },
    {
      crime: 'Fel. Assault',
      location: 'New York City',
      year: 2023,
      cases: 27828,
    },
    {
      crime: 'Burglary',
      location: 'New York City',
      year: 2023,
      cases: 13750,
    },
    {
      crime: 'Rape',
      location: 'New York City',
      year: 2024,
      cases: 1736,
    },
    {
      crime: 'Robbery',
      location: 'New York City',
      year: 2024,
      cases: 16465,
    },
    {
      crime: 'Fel. Assault',
      location: 'New York City',
      year: 2024,
      cases: 29194,
    },
    {
      crime: 'Burglary',
      location: 'New York City',
      year: 2024,
      cases: 13750,
    },
    {
      crime: 'Murder',
      location: 'New York City',
      year: 1990,
      cases: 2262,
    },
    {
      crime: 'Murder',
      location: 'New York City',
      year: 1993,
      cases: 1927,
    },
    {
      crime: 'Murder',
      location: 'New York City',
      year: 1998,
      cases: 629,
    },
    {
      crime: 'Murder',
      location: 'New York City',
      year: 2001,
      cases: 649,
    },
    {
      crime: 'Rape',
      location: 'New York City',
      year: 2001,
      cases: 1930,
    },
    {
      crime: 'Rape',
      location: 'New York City',
      year: 1998,
      cases: 2476,
    },
    {
      crime: 'Rape',
      location: 'New York City',
      year: 1993,
      cases: 3225,
    },
    {
      crime: 'Rape',
      location: 'New York City',
      year: 1990,
      cases: 3126,
    },
    {
      crime: 'Robbery',
      location: 'New York City',
      year: 2001,
      cases: 27873,
    },
    {
      crime: 'Robbery',
      location: 'New York City',
      year: 1998,
      cases: 39003,
    },{
      crime: 'Robbery',
      location: 'New York City',
      year: 1993,
      cases: 85892,
    },
    {
      crime: 'Robbery',
      location: 'New York City',
      year: 1990,
      cases: 100280,
    },
    {
      crime: 'Fel. Assault',
      location: 'New York City',
      year: 2001,
      cases: 23020,
    },
    {
      crime: 'Fel. Assault',
      location: 'New York City',
      year: 1998,
      cases: 28848,
    },
    {
      crime: 'Fel. Assault',
      location: 'New York City',
      year: 1993,
      cases: 41121,
    },
    {
      crime: 'Fel. Assault',
      location: 'New York City',
      year: 1990,
      cases: 44122,
    },
    {
      crime: 'Burglary',
      location: 'New York City',
      year: 2001,
      cases: 32694,
    },
    {
      crime: 'Burglary',
      location: 'New York City',
      year: 1998,
      cases: 47181,
    },
    {
      crime: 'Burglary',
      location: 'New York City',
      year: 1993,
      cases: 100936,
    },
    {
      crime: 'Burglary',
      location: 'New York City',
      year: 1990,
      cases: 122055,
    },
  ];

export default crimes